name: Test - Action (local)
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  get-versions:
    uses: ./.github/workflows/get-versions.yaml

  click:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: click
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).click) }}

  jax:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: jax
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).jax) }}

  matplotlib:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: matplotlib
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).matplotlib) }}

  numpy:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: numpy
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).numpy) }}

  pandas:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: pandas
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).pandas) }}

  pyarrow:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: pyarrow
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).pyarrow) }}

  requests:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: requests
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).requests) }}

  safetensors:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: safetensors
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).safetensors) }}

  scikit-learn:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: scikit-learn
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).scikit-learn) }}

  scipy:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: scipy
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).scipy) }}

  torch:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: torch
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).torch) }}

  xarray:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: xarray
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).xarray) }}
