name: Test - Action (local)
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  get-versions:
    uses: ./.github/workflows/get-versions.yaml

  click:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: click
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).click) }}

  jax:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: jax
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).jax) }}

  matplotlib:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: matplotlib
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).matplotlib) }}

  numpy:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: numpy
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).numpy) }}

  pandas:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: pandas
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).pandas) }}

  pyarrow:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: pyarrow
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).pyarrow) }}

  requests:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: requests
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).requests) }}

  safetensors:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: safetensors
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).safetensors) }}

  scikit-learn:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: scikit-learn
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).scikit-learn) }}

  scipy:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: scipy
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).scipy) }}

  torch:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: torch
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).torch) }}

  xarray:
    needs: get-versions
    uses: ./.github/workflows/test-local-action.yaml
    with:
      package-name: xarray
      package-versions: ${{ toJson(fromJson(needs.get-versions.outputs.package_versions).xarray) }}


  ######################
  #     Edge cases     #
  ######################

  python-version-with-feature:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          activate-environment: true

      - name: Install packages
        run: |
          uv pip install pytest

      - name: Install valid package version
        uses: ./
        with:
          package-name: numpy
          package-version: 2.4
          python-version: '3.13.0'

      - name: Run functional tests
        run: |
          python -m pytest tests/functional


  no-python-version:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          activate-environment: true

      - name: Install packages
        run: |
          uv pip install pytest

      - name: Install valid package version
        uses: ./
        with:
          package-name: numpy
          package-version: 2.4

      - name: Run functional tests
        run: |
          python -m pytest tests/functional


  incorrect-python-version:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          activate-environment: true

      - name: Install valid package version
        uses: ./
        id: install-package
        with:
          package-name: numpy
          package-version: 2.4
          python-version: v3.14

      - name: Failure - it did not fail as expected
        if: steps.install-package.outcome != 'failure'
        run: |
          echo "❌ Error: Step should have failed but didn't!"
          exit 1

      - name: Success - it failed as expected
        if: steps.install-package.outcome == 'failure'
        run: echo "✅ Test passed - step failed as expected"
