name: Test Local Action with Dependency Version
on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true
      package-versions:
        type: string
        required: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.14', '3.13', '3.12', '3.11', '3.10' ]
        package-version: ${{ fromJson(inputs.package-versions) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Install packages
        run: |
          uv pip install pytest

      - name: Install valid package version
        uses: ./
        with:
          package-name: ${{ inputs.package-name }}
          package-version: ${{ matrix.package-version }}
          python-version: ${{ matrix.python-version }}

      - name: Run functional tests
        run: |
          python -m pytest tests/functional


  python-version-with-feature:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          activate-environment: true

      - name: Install packages
        run: |
          uv pip install pytest

      - name: Install valid package version
        uses: ./
        with:
          package-name: numpy
          package-version: 2.4
          python-version: ${{ matrix.python-version }}.0

      - name: Run functional tests
        run: |
          python -m pytest tests/functional


  no-python-version:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          activate-environment: true

      - name: Install packages
        run: |
          uv pip install pytest

      - name: Install valid package version
        uses: ./
        with:
          package-name: numpy
          package-version: 2.4

      - name: Run functional tests
        run: |
          python -m pytest tests/functional


  incorrect-python-version:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'
          activate-environment: true

      - name: Install valid package version
        uses: ./
        id: install-package
        with:
          package-name: numpy
          package-version: 2.4
          python-version: v3.14

      - name: Failure - it did not fail as expected
        if: steps.install-package.outcome != 'failure'
        run: |
          echo "❌ Error: Step should have failed but didn't!"
          exit 1

      - name: Success - it failed as expected
        if: steps.install-package.outcome == 'failure'
        run: echo "✅ Test passed - step failed as expected"
